# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startdate',
            field=models.DateField(),
        ),
    ]
